/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package core.gui.admon;

import core.controller.MainController;
import core.data.ActiveSession;
import core.data.Classroom;
import core.data.ClientModel;
import core.data.FileD;
import core.data.FilesSession;
import core.data.ServerFile;
import core.data.Session;
import core.data.User;
import java.beans.PropertyVetoException;
import java.io.File;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.regex.Pattern;
import core.webservices.OpenFileService;

/**
 *
 * @author Diana
 */
public class ClassroomInter extends javax.swing.JFrame {
    private static ClassroomInter instance;
    private User user = new User();
    private Classroom classToProject;
    /**
     * Creates new form Classroom
     */
    public ClassroomInter( User user, Classroom classroom, boolean presentation) throws PropertyVetoException {
        String path;
        initComponents();
        classToProject = classroom;
        this.user = user;
        if (true) {
            path = "";
            //path = classToProject.getRootFolder() + "\\" + user.getUserName();
            toProjectSession(path);
//            }
        }else{
            logText.setText("No es aula...");
        }
        
    }
    
    public void toProjectSession(String path) {
        FilesSession filesess;
        FileD doc;
        String[] aux;
        String subject, pathTemp;
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
        LocalDateTime firstDate = LocalDateTime.now();
        LocalDateTime lastDate = LocalDateTime.now().plusHours(2);
        
        ArrayList<ActiveSession> sessionToday = MainController.getActiveSessionsDates(user.getId(), dtf.format(firstDate), dtf.format(lastDate));
        
        for (ActiveSession s : sessionToday) {
            
            System.out.println(s.getPathFile());
 
            File file = new File(s.getPathFile());
            if (file.exists()) {
                OpenFileService.openFile(s.getPathFile());
                //MainController.getFileToOpen(doc.getFileName(), doc.getPath());
            } else {
                
            }
        }
        if (sessionToday.size()==0){
            logText.setText("No hay sesiones...");
        }
    }
    
     public static ClassroomInter getInstance(User user, Classroom classroom, boolean presentation) throws PropertyVetoException {
        if (instance == null) {
            instance = new ClassroomInter(user, classroom, presentation);
        }
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(logText, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(logText, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(150, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel logText;
    // End of variables declaration//GEN-END:variables
}
