/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package core.main;

import java.util.ArrayList;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Luis
 */
public class Descargas extends javax.swing.JDialog implements DownloadListener{

    /**
     * Creates new form Descargas
     */
    private static JTable table;
    private static DefaultTableModel model;
    public static ArrayList<String> descargas;
    
    private static Descargas descargasFrame;
    
    private Descargas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        descargas = new ArrayList();
        model = new DefaultTableModel();
        model.addColumn("Archivo");
        model.addColumn("Estado");
        table = this.jTable1;
        table.setModel(model);
        
        setLocationRelativeTo(null);
        setAlwaysOnTop(true);
        
    }
    
    public static Descargas getInstance(){
        if(descargasFrame == null){
            descargasFrame = new Descargas(null, false);
        }
        
        return descargasFrame;
    }
    
    public void update(){
        model = (DefaultTableModel) table.getModel();
        model.setRowCount(0);
        
        for (String name:descargas) {
            model.addRow(new String[]{name,"Descargando..."});
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Descargas activas");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Archivo", "Estado"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void downloadStart(String file) {
        if(!isVisible()){
            setVisible(true);
        }
        descargas.add(file);
        update();
        
    }

    @Override
    public void downloadEnd(String file) {
        descargas.remove(file);
        update();

    }


}
