/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package core.main;

import core.controller.MainController;
import core.data.Classroom;
import core.data.Subscription;
import core.data.User;
import core.data.YellowPage;
import core.db.rqlite.RQLiteConnection;
import core.utils.Host;
import core.webservices.NotificationServer;
import java.io.BufferedReader;
import java.io.FileReader;
import java.net.InetAddress;
import java.net.UnknownHostException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Diana
 */
public class AudienciaAgent extends javax.swing.JFrame {

    /**
     * Creates new form AudienciaAgent
     */
    private User user;
    private ArrayList<Subscription> subscriptions;
    private ArrayList<Classroom> classrooms;

    public AudienciaAgent() {
        try {
            RQLiteConnection.getInstance().conectar();
            initComponents();
            setupAgent();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AudienciaAgent.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void setupAgent() {
        ArrayList<Host> conf = setAgent();
        for (Host host : conf) {
            new NotificationServer(host.getAddress(), host.getPort(), user, txtArea).start();
        }
        if (conf.isEmpty()) {
            txtArea.setText("No hay registros de cursos...");
        } else {
            txtArea.setText("Monitoreando...");
        }
    }

    public ArrayList<Host> setAgent() {
        YellowPage yPage;
        ArrayList<Host> hosts = new ArrayList<>();
        String username;
        username = readUsername();
        user = MainController.existUserName(username);
        if (user != null) {
            yPage = MainController.existsServiceYP(username, YellowPage.AUDIENCIA);
            if (yPage == null) {
                MainController.addServicesYP(user.getLocation(), username, YellowPage.AUDIENCIA); // ip,nombre,tipo de servicio
            }
            System.out.println(user.getHostcomputer());
            subscriptions = MainController.getSubscriptionUserId(user.getId());
            for (Subscription subs : subscriptions) {
                if (!subs.getPortHostProf().isEmpty()) {
                    hosts.add(new Host(subs.getHostProfesor(), Integer.parseInt(subs.getPortHostProf())));
                }
            }
        }
        classrooms = MainController.getClassrooms();
        for (Classroom clas : classrooms) {
            if (isInteger(clas.getPort())) {
                hosts.add(new Host(clas.getLocation(), Integer.parseInt(clas.getPort())));
            }
        }
        return hosts;
    }

    public String readUsername() {
        String line;
        ArrayList<Host> hosts = new ArrayList<>();
        String username;
        try {
            BufferedReader br = new BufferedReader(new FileReader("user.txt"));

            username = br.readLine().split("\\s+")[0].trim();
            System.out.println(username);
            return username;

        } catch (Exception ex) {
            Logger.getLogger(AudienciaAgent.class.getName()).log(Level.SEVERE, null, ex);
        }

        return null;
    }

    private boolean isInteger(String input) {
        try {
            Integer.parseInt(input);
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Agente -Audi");

        jScrollPane1.setPreferredSize(new java.awt.Dimension(400, 400));

        txtArea.setEditable(false);
        txtArea.setColumns(20);
        txtArea.setRows(5);
        jScrollPane1.setViewportView(txtArea);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AudienciaAgent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AudienciaAgent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AudienciaAgent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AudienciaAgent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AudienciaAgent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtArea;
    // End of variables declaration//GEN-END:variables
}
