/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fileserviceclient;

import core.controller.MainController;
import core.data.ModelAgent;
import core.db.rqlite.RQLiteConnection;
import core.fileserver.FileServer;
import core.queue.EventQueueServer;
import core.server.ActionServer;
import java.io.BufferedReader;
import java.io.FileReader;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Diana
 */
public class AgentConferencista extends javax.swing.JFrame {

    /**
     * Creates new form AgentConferencista
     */
    private String agentType;
    private String agentname;

    public AgentConferencista() {
        try {
            RQLiteConnection.getInstance().conectar();
            initComponents();
            setupAgent();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AgentConferencista.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public Boolean readUsername() {

        try {
            BufferedReader br = new BufferedReader(new FileReader("Config1.txt"));  // 
            //tipo de agente (CONFERENCISTA | AUDIENCIA | SALON)
            this.agentType = br.readLine().split("\\s+")[0].trim();
            // agentname o hostname(classroom)          
            this.agentname = br.readLine().split("\\s+")[0].trim();
            System.out.println(agentname);

        } catch (Exception ex) {
            Logger.getLogger(AgentConferencista.class.getName()).log(Level.SEVERE, null, ex);
            return false;
        }
        return true;
    }

    public void setupAgent() {
        try {
            
            if (readUsername()) {
                this.setTitle(agentType);
                ModelAgent agent = new ModelAgent();
                agent.setConfigAgent(agentType, agentname);              
                if (agent.getyPage() == null) {
                    MainController.addServicesYP(agent.getIp(), agentname, agent.getType(), agent.getPort()); // ip,nombre,tipo de servicio, port
                }

                EventQueueServer server = new EventQueueServer(this.txtA_msg,agent,10009);
                ActionServer actionServer = new ActionServer(this.txtA_msg,agent,Integer.parseInt(agent.getPort()));

//            if (user != null && isInteger(user.getPort())) {
//                nserver = new EventQueueNotificationServer(Integer.parseInt(user.getPort()), this.txtA_msg);
//            } else {
//                nserver = new EventQueueNotificationServer(10002, this.txtA_msg);
//            }
                FileServer fileServer = new FileServer(this.txtA_msg, 5002,agent );

                //server.start();
                actionServer.start();
                fileServer.start();
            }
        } catch (Exception ex) {
            System.out.println(ex.getLocalizedMessage());
        }
    }

    private boolean isInteger(String input) {
        try {
            Integer.parseInt(input);
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtA_msg = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Agente-Conf");
        setPreferredSize(new java.awt.Dimension(400, 400));

        txtA_msg.setEditable(false);
        txtA_msg.setColumns(20);
        txtA_msg.setRows(5);
        txtA_msg.setPreferredSize(new java.awt.Dimension(400, 400));
        jScrollPane1.setViewportView(txtA_msg);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgentConferencista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgentConferencista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgentConferencista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgentConferencista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgentConferencista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtA_msg;
    // End of variables declaration//GEN-END:variables
}
